In [1]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive/My Drive/colabpractice/dcbot
!pip install db-sqlite3
import pandas as pd
import sqlite3
from datetime import date

Mounted at /gdrive
/gdrive/My Drive/colabpractice/dcbot
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting db-sqlite3
  Downloading db-sqlite3-0.0.1.tar.gz (1.4 kB)
Collecting db
  Downloading db-0.1.1.tar.gz (3.4 kB)
Collecting antiorm
  Downloading antiorm-1.2.1.tar.gz (171 kB)
     |████████████████████████████████| 171 kB 4.9 MB/s
Building wheels for collected packages: db-sqlite3, db, antiorm
  Building wheel for db-sqlite3 (setup.py) ... done
  Created wheel for db-sqlite3: filename=db_sqlite3-0.0.1-py3-none-any.whl size=1794 sha256=fee08cf27a0b41cdc2602595bca90671c30c512509d6c91a954d982c1eceb4b9
  Stored in directory: /root/.cache/pip/wheels/02/38/d5/2f54461050571bf5330fee2a37ab1c9b5e7540b0572f1acdab
  Building wheel for db (setup.py) ... done
  Created wheel for db: filename=db-0.1.1-py3-none-any.whl size=3895 sha256=d647ab7e570389b4a598e956c16103561998cc9309b9b584614e7681786460c8
  Stored in directory: /root/.cache/pip/wheels/8e/97/82/741d2b360507411ec233d0280d7371faa94b03bde834e4a9be
  Building wheel for antiorm (setup.py) ... done
  Created wheel for antiorm: filename=antiorm-1.2.1-py3-none-any.whl size=31679 sha256=5708eb399f5ea7db18b6d48f57573255ec7958526f5122be7f011d8837d80ffc
  Stored in directory: /root/.cache/pip/wheels/c5/43/70/e9729370cfff40c49d3e3d05377d54b3ecd71f64e62341ea80
Successfully built db-sqlite3 db antiorm
Installing collected packages: antiorm, db, db-sqlite3
Successfully installed antiorm-1.2.1 db-0.1.1 db-sqlite3-0.0.1

In [ ]:
# db = sqlite3.connect("data/pokemon.db")
# db.execute("drop table if exists pokemon")
# try:
#   db.execute("create table pokemon(id text,name text,typea text,typeb text, level int, hp int,speed int,atk int ,def int,spatk int,spdef int,money int,exp int)")
# except:
#   print("Already table existed !!")

In [2]:
db = sqlite3.connect("data/pokemon.db")

In [ ]:
import json
import os
with open(os.path.join("./data/", "pokemon.json"), newline='', encoding='UTF-8') as jsonfile:
    pokemon = json.load(jsonfile)
    jsonfile.close()
status = { }
for user in pokemon.keys():
    id=user
    name=pokemon[user][0]
    hisstatus=pokemon[user][1]
    atype=hisstatus[7]
    btype=""
    level=hisstatus[6]
    hp=hisstatus[0]
    speed=hisstatus[5]
    atk=hisstatus[1]
    defv=hisstatus[2]
    spatk=hisstatus[3]
    spdef=hisstatus[4]
    money=0
    exp=0
    
    cmd = "insert into pokemon(id	,name,typea,typeb,level,hp,	speed,	atk,	def,	spatk,	spdef,	money,	exp) values('{}','{}','{}','{}','{}','{}','{}','{}','{}','{}','{}','{}','{}')".format(id,name,atype,btype,level,hp,speed,atk,defv,spatk,spdef,money,exp)
    db.execute(cmd)
    db.commit()

In [6]:
id='534243081135063041'

qry = f"SELECT * FROM pokemon where id='{id}'"

df = pd.read_sql_query(qry, db)

df.head()

# db.execute(f"update pokemon set exp=100 where id={id}");

,id,name,typea,typeb,level,hp,speed,atk,def,spatk,spdef,money,exp
0,534243081135063041,伊莉亞,草,,5,58,59,50,54,42,47,500,0

In [5]:
id='534243081135063041'
qry = f"SELECT * FROM pokemon where id={id} "
# print(qry)
df = pd.read_sql_query(qry, db)

money=df['money'][0]
print(money)
cmd=f"update pokemon set money={money+100} where id={id};"

db.execute(cmd)
db.commit()

400